version: '2'
services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/12345
      - NEO4J_dbms_memory_heap_maxSize=1024
  transaction-emulator:
    build: ./transaction-emulator
    environment:
      - NODE_ENV=production
      - NEO4J_URL=bolt://neo4j
    depends_on:
      - neo4j
  api-server:
    build: ./api-server
    environment:
      - NODE_ENV=production
      - PORT=5000
      - NEO4J_URL=bolt://neo4j
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
